# Generated by Django 6.0.4 on 2026-05-24 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='design_file',
            field=models.FileField(blank=True, null=True, upload_to='order_designs/'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='design_note',
            field=models.TextField(blank=True),
        ),
    ]
