# Generated by Django 6.0.4 on 2026-07-01 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_refundrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='refundrequest',
            name='proof_image',
            field=models.ImageField(blank=True, null=True, upload_to='refund_proofs/'),
        ),
    ]
