# Generated by Django 6.0.4 on 2026-05-17 01:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('bca_va', 'BCA Virtual Account'), ('mandiri_bill', 'Mandiri Bill'), ('qris', 'QRIS'), ('gopay', 'GoPay'), ('ovo', 'OVO')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Menunggu'), ('completed', 'Berhasil'), ('failed', 'Gagal'), ('expired', 'Kadaluarsa')], default='pending', max_length=20)),
                ('amount', models.DecimalField(decimal_places=0, max_digits=12)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='orders.order')),
            ],
        ),
    ]
