# Generated by Django 6.0.4 on 2026-07-05 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='snap_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
